### ISSUE TITLE
3.1.0 tag and update repo

### ISSUE THREAD

**Issue by leela52452** [AntonioRedondo/AnotherMonitor#11]
@AntonioRedondo 
google play 3.1.0
can you please update repo for 3.1.0 and create tag, version code & name.

**Comment by AntonioRedondo** [comment]
Hey @leela52452,
I don't have much time at the moment to do it. But if you open a pull request with working changes I'll merge them to master.

**Comment by nowshad-hasan** [comment]
Hey @AntonioRedondo, will you mind if I work on to update the repo with build tools 'com.android.tools.build:gradle:3.5.3', target sdk to 29, migrate to androidx, java version update to 1.8? Actually I'm very new to open source and trying to find some easy stuffs to do. Thanks.

**Comment by AntonioRedondo** [comment]
Hello @nowshad-hasan, 
That would be great! If you open a pull request with the changes I'll definitively merge it.

**Comment by nowshad-hasan** [comment]
Hi @AntonioRedondo, I've made some changes regarding these issues:
1. Create a notification channel for devices>=Oreo
2. Remove version related useless code from manifest and gradle files
3. Migrate to androidx.
4. Update gradle distribution to 5.4.1
5. Update gradle build to 3.5.3
6. Make TargetSdkVersion to 29(android 10)
7. Make source compatibility to JAVA 1.8

And do you want me to update version code from 9 to 10 and version name to 3.1.0 to 3.2.0 or something other? Just confirm me, so that I can make a PR with all of these changes.

**Comment by AntonioRedondo** [comment]
Since this seems version bump ups and doesn't have new user features I think it would be better to set the version as 3.1.1. However I'm cannot be 100% sure until I see the pull request.

**Comment by AntonioRedondo** [comment]
Closing this issue as it has been fixed on https://github.com/AntonioRedondo/AnotherMonitor/pull/12
